version: '3'
services:
  mailhog:
          image: mailhog/mailhog
          ports:
              - 8025:8025
              - 1025:1025
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
      # - ./mail.ini:/etc/php.d/mail.ini:ro
    ports:
      - "81:80"
    depends_on:
      - db

  db:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pass